config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    get '/users/sign_in' => 'user/sessions#destroy'
	root 'pages#index'
	resources :articles do
		resources :comments
	
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	belongs_to :user, :optional => true
	validates :title, presence: true, length: { minimum: 3, maximum: 50 }
 validates :description, presence: true, length: { minimum: 10, maximum: 300 } 
 has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  

end

app/models/user.rb
class User < ApplicationRecord

	has_many :articles
	has_many :users, dependent: :destroy
  has_many :comments, dependent: :destroy
  # Include default devise modules. Others available are:
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  
  def index
  @articles = current_user.articles.order('id desc').paginate(page: params[:page ], per_page: 5)
  end 
	def new
		@article = current_user.articles.new	
	end

	def create
 	 	@article = current_user.articles.new(article_params)
  
  	if @article.save
   	flash[:notice] = "Article was successfully created"
   	redirect_to article_path(@article)
  else
   render 'new'
  end
 end

 def show
  
 end

 def edit

 	
 end

 def update
  
  if @article.update(article_params)
   flash[:notice] = "Article was updated"
   redirect_to article_path(@article)
  else
   flash[:notice] = "Article was not updated"
   render 'edit'
  end
end

def destroy
  @article.destroy
  flash[:notice] = "Article was deleted"
  redirect_to articles_path
 end

private
  def article_params
   params.require(:article).permit(:title, :description, :image)
  end

  def set_article
   @article = Article.find(params[:id])
end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def index
		@comment = Comment.all
	end

  def new
    @article = Article.find(params[:article_id])
  @comment = Comment.new(params[:article])
  end

	def create
		@article = Article.find(params[:article_id])
		@comment = @article.comments.create(params[:comment].permit(:name, :body))
     if @comment.save
    	redirect_to article_path(@article)
    else
      render 'new'
    end
    
  end
def show
  #@comment = Comment.find(params[:id])
end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	
			
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
 <div class="row">
  <div class="col-xs-8 col-xs-offset-2">
   <div class="panel panel-danger">
    <div class="panel-heading">
     <h2 class="panel-title">
      <%= pluralize(@article.errors.count, "error") %>
      prohibited this article from being saved:
     </h2>
     <div class="panel-body"> 
      <ul>
       <% @article.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
       <% end %>
      </ul>
     </div>
    </div>
   </div>
  </div>
 </div>
<% end %>

<div class="row">
 <div class="col-xs-12">
  <%= form_for(@article, :html => { multipart: true, class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :title %>
   </div>
   <div class="col-sm-6">
    <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
   </div>
  </div>
</div>
</div>

  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :image %>
  </div>
    <div class="col-sm-6">
    <%= f.file_field :image, class: "form-control", placeholder: "Title of article", autofocus: true %>
   </div>
  </div>
<br><br>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :description %>
   </div>
   <div class="col-sm-6">
    <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
   </div>
  </div>
  <br><br>
  <div class="form-group">
   <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit class: 'btn btn-primary btn-large' %>
   </div>
  </div>
<% end %>
 </div>
</div>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<%= render 'form' %>
<div align="center">
<%= link_to 'Back', articles_path, class: "btn btn-xs btn-success" %>
</div>

app/views/articles/index.html.erb
<h1 align="center">Listing all articles</h1>
<div align="center">
<%= will_paginate @articles %>
</div>
<% @articles.each do |article| %>
 <div class="row">
  <div class="col-xs-8 col-xs-offset-2">
   <div class="well well-lg">
    <div class="article-title">
     <%= link_to article.title, article_path(article) %>
    </div>
    <div class="article-body">
     <%= truncate(article.description, length: 10) %>
      <%= link_to 'read more', @article %> 
    </div>
    <!--<div class="article-actions">
     <%= link_to "Edit", edit_article_path(article), class: "btn btn-xs btn-primary" %>
     <%= link_to "Delete", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
    </div>!-->
   </div>
  </div>
 </div>
<% end %>

app/views/articles/new.html.erb
<div align="center"><h1>Create  Article</h1></div>
<%= render 'form' %>

<%= link_to 'Back', articles_path, class: "btn btn-xs btn-success" %>

app/views/articles/show.html.erb
<h1>Showing selected article</h1>
<p>
 Title: <%= simple_format(@article.title) %>
</p>
<p>
	Image: <%= image_tag @article.image.url(:medium) %>
</p>
<p>
 Description: <%= simple_format(@article.description) %>
</p>
<br>
<%= link_to "Edit", edit_article_path(@article), class: "btn btn-xs btn-primary" %> 
<%= link_to 'Back', articles_path, class: "btn btn-xs btn-success" %>
<%= link_to "Delete", article_path(@article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
<%= link_to "Add Comment", new_article_comment_path(article_id: @article.id),  class: "btn btn-xs btn-success" %>

	<br>
	<% if @article.comments.any? %>
	<h2>Comments <%= @article.comments.count %> </h2>
	<%= render @article.comments %>

<% end %>

app/views/comments/_comment.html.erb
<%= comment.name %>
<%= comment.body %>

app/views/comments/_form.html.erb
<%= form_for([@article,@article.comments.build]) do |f| %>
<p>
	<%= f.label :name %>
	<%= f.text_field :name %>
</p>
<p>
	<%= f.label :body %><br>
	<%= f.text_area :body %>
</p>
<br>
<p>
	<%= f.submit %>
</p>
<% end %>

app/views/comments/new.html.erb
<div align="center"><h1> Create Comment </h1></div>
<%= render 'form' %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">JYOTI BLOG</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
    
        
        <% if user_signed_in? %>
        <li><%= link_to "Articles", articles_path %></li>
        <li><%= link_to "Create Article", new_article_path %></li>
        <li><%= link_to 'My Account', edit_user_registration_path  %></li>
          <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
          <% else %>
          <li><%= link_to 'Login', new_user_session_path  %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path  %></li>
        <% end %>
        
      </ul>
      
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <% flash.each do |name, msg| %>
    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    
    <ul>
     <li><%= msg %></li>
    </ul>
<% end %>
    
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<div class='home-content-wrapper'>
  <h1 class='home-motto'>Welcome To Jyoti Blog</h1>


</div>